# Generated by Django 3.1.3 on 2020-11-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_project_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subtitle',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
